import type { Metadata } from 'next';
import { Roboto } from 'next/font/google';
import './globals.css';
import { Inter, Montserrat, Space_Mono } from 'next/font/google';

const inter = Inter({
  subsets: ['latin'],
  variable: '--inter',
});

const montserrat = Montserrat({
  subsets: ['latin'],
  variable: '--montserrat',
});
const space_Mono = Space_Mono({
  subsets: ['latin'],
  variable: '--space_mono',
  weight: ['400'],
});

const roboto = Roboto({
  subsets: ['latin'],
  weight: ['400', '500', '700'], // choose the weights you need
  variable: '--font-roboto', // optional if you want to use it in CSS
});

export const metadata: Metadata = {
  title: 'My App',
  description: 'Generated by Next.js',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${inter.variable} ${montserrat.variable} ${space_Mono.variable} ${roboto.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
